version: "3"
services:
  web:
    volumes:
      - ../:/usr/share/nginx/html
    build:
      context: ../
      dockerfile: ./Dockerfile
    image: local-image
    container_name: local-container
    env_file:
      - ../.env
    ports:
      - "80:80"
    networks:
      - mynetwork
networks:
  mynetwork:
