version: "3"
services:
  web:
    image: heathn/my-application:latest
    env_file:
      - .env
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 10
    ports:
      - "80:80"
    networks:
      - mynetwork
networks:
  mynetwork:
