version: "3"
services:
  web:
    build:
      context: ../
      dockerfile: ./DockerfileBuildDeployImage
    image: image-untagged
    ports:
      - "80:80"
    networks:
      - mynetwork
networks:
  mynetwork:
